name: hamaraservice_customer
description: HamaraService - Book Home Services
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.3
  firebase_database: ^10.2.4
  shared_preferences: ^2.1.2
  http: ^1.1.0
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
