// This file is auto-generated by GitHub Actions from secrets.
// Do NOT commit real values here.
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: '1064274729048',
    projectId: 'hamaraservice-s009',
    databaseURL:
        'https://hamaraservice-s009-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hamaraservice-s009.firebasestorage.app',
  );
}
